# Generated by Django 3.2.5 on 2023-11-15 13:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mesure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('humidite', models.DecimalField(decimal_places=2, max_digits=5)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Pression',
            fields=[
                ('mesure_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='appcapteur.mesure')),
                ('nom_capteur', models.CharField(max_length=255)),
                ('donnee_enregistree', models.FloatField()),
                ('timestamp_pression', models.DateTimeField(auto_now_add=True)),
            ],
            bases=('appcapteur.mesure',),
        ),
        migrations.CreateModel(
            name='Temperature',
            fields=[
                ('mesure_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='appcapteur.mesure')),
                ('nom_capteur', models.CharField(max_length=255)),
                ('donnee_enregistree', models.FloatField()),
                ('timestamp_temperature', models.DateTimeField(auto_now_add=True)),
            ],
            bases=('appcapteur.mesure',),
        ),
    ]
